services:
  synctube:
    build: .
    container_name: SyncTube
    user: 99:100
    # ports:
      # - :4200/tcp
    networks:
      - proxy
    volumes:
      - /mnt/user/appdata/SyncTube:/usr/src/app/user

networks:
  proxy:
    external: true
